// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SystemMain;

#nullable disable

namespace SystemMain.Migrations
{
    [DbContext(typeof(SystemMainDbContext))]
    [Migration("20260301152832_SystemMainInit")]
    partial class SystemMainInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SystemMain.Entities.Controller", b =>
                {
                    b.Property<string>("ControllerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("控制器編號");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("控制器名稱");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("建立時間");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasComment("是否啟用");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("更新日期");

                    b.HasKey("ControllerId");

                    b.HasIndex("IsEnable")
                        .HasDatabaseName("IX_APIController_IsEnable")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("Controller");

                    b.HasData(
                        new
                        {
                            ControllerId = "Controller",
                            ControllerName = "功能設定",
                            CreateDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEnable = true
                        },
                        new
                        {
                            ControllerId = "LogIn",
                            ControllerName = "登入",
                            CreateDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEnable = true
                        },
                        new
                        {
                            ControllerId = "SignIn",
                            ControllerName = "註冊",
                            CreateDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEnable = true
                        },
                        new
                        {
                            ControllerId = "UserRolePermission",
                            ControllerName = "角色權限",
                            CreateDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEnable = true
                        },
                        new
                        {
                            ControllerId = "UserRole",
                            ControllerName = "使用者角色",
                            CreateDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEnable = true
                        });
                });

            modelBuilder.Entity("SystemMain.Entities.LogInRecord", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasComment("使用者編號");

                    b.Property<string>("Token")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasComment("Token");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("建立時間");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasComment("是否啟用");

                    b.HasKey("UserId", "Token")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("IsEnable")
                        .HasDatabaseName("IX_LogInRecord_IsEnable")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("LogInRecord");
                });

            modelBuilder.Entity("SystemMain.Entities.UserInfo", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasComment("使用者帳號");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("建立時間");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasComment("電子信箱");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("是否為管理者");

                    b.Property<bool>("IsVerify")
                        .HasColumnType("boolean")
                        .HasComment("是否驗證");

                    b.Property<string>("Memo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("備註");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("名稱");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("密碼");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("電話");

                    b.Property<string>("Photo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("頭貼");

                    b.Property<int>("SSOType")
                        .HasColumnType("integer")
                        .HasComment("第三方登入方式");

                    b.Property<string>("StatusMemo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("2")
                        .HasComment("狀態備註");

                    b.Property<string>("TimeZoneID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("時區ID");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("更新日期");

                    b.Property<short>("UserStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasComment("帳號狀態");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("驗證碼");

                    b.Property<DateTime?>("VerificationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("驗證日期");

                    b.HasKey("UserId");

                    b.HasIndex("IsAdmin")
                        .HasDatabaseName("IX_UserInfo_IsAdmin")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("IsVerify")
                        .HasDatabaseName("IX_UserInfo_IsVerify")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("SSOType")
                        .HasDatabaseName("IX_UserInfo_SSOType")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("UserStatus")
                        .HasDatabaseName("IX_UserInfo_UserStatus")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("UserInfo");

                    b.HasData(
                        new
                        {
                            UserId = "TEST@test.com",
                            CreateDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAdmin = true,
                            IsVerify = true,
                            Name = "TESTUser",
                            Password = "zBid3apzguMvkuuvaV3ew7JWYtxkukVN2As7P5aDKLg=",
                            SSOType = 0,
                            TimeZoneID = "Taipei Standard Time",
                            UserStatus = (short)1
                        });
                });

            modelBuilder.Entity("SystemMain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("角色編號");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("建立時間");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasComment("是否啟用");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("角色名稱");

                    b.Property<short>("RoleOrder")
                        .HasColumnType("smallint")
                        .HasComment("角色順位");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("更新日期");

                    b.HasKey("RoleId");

                    b.HasIndex("IsEnable")
                        .HasDatabaseName("IX_UserRole_IsEnable")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("RoleOrder")
                        .HasDatabaseName("IX_UserRole_RoleOrder")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("544cc745-6a1c-9937-9638-a53a1bd524fd"),
                            CreateDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEnable = true,
                            RoleName = "第一級",
                            RoleOrder = (short)1
                        },
                        new
                        {
                            RoleId = new Guid("dfa8f949-153a-7739-b659-0fbd3cbe502c"),
                            CreateDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEnable = true,
                            RoleName = "第二級",
                            RoleOrder = (short)2
                        },
                        new
                        {
                            RoleId = new Guid("c447d771-ac6c-1d30-af0f-fbb734171512"),
                            CreateDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEnable = true,
                            RoleName = "第三級",
                            RoleOrder = (short)3
                        });
                });

            modelBuilder.Entity("SystemMain.Entities.UserRoleBinding", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasComment("使用者編號");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasComment("角色編號");

                    b.Property<string>("ControllerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("控制器編號");

                    b.Property<bool>("CreateAllowed")
                        .HasColumnType("boolean")
                        .HasComment("是否允許新增");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("建立時間");

                    b.Property<bool>("DeleteAllowed")
                        .HasColumnType("boolean")
                        .HasComment("是否允許刪除");

                    b.Property<bool>("QueryAllowed")
                        .HasColumnType("boolean")
                        .HasComment("是否允許查詢");

                    b.Property<bool>("UpdateAllowed")
                        .HasColumnType("boolean")
                        .HasComment("是否允許更新");

                    b.HasKey("UserId", "RoleId", "ControllerId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("UserRoleBinding");
                });
#pragma warning restore 612, 618
        }
    }
}
